framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        gc_probability: 0
        cookie_secure: auto
        cookie_samesite: lax
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            cache.annotations:
                adapter: cache.app
    php_errors:
        log: true
