# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        gc_probability: 0
        cookie_secure: true
        cookie_samesite: ~
        use_cookies: true
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    http_method_override: false
    http_client:
        default_options:
            verify_peer: false
            verify_host: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: '%env(string:REDIS_URL)%'
            pools:
                cache.annotations:
                    adapter: cache.app