framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        gc_probability: 0
        cookie_secure: true
        cookie_samesite: ~
        use_cookies: true
        storage_factory_id: session.storage.factory.native
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            cache.annotations:
                adapter: cache.app
    php_errors:
        log: true
    form:
        legacy_error_messages: false