twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: true
    exception_controller: null

when@dev:
    twig:
        auto_reload: true