image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:webapp:
  stage: build
  tags:
    - docker
  script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" docker/app/Dockerfile
    - sed -i "s/:master/:latest/g" docker/app/Dockerfile
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      -f docker/app/Dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:latest

build:encore:
  stage: build
  tags:
    - docker
  script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" docker/encore/Dockerfile
    - sed -i "s/:master/:latest/g" docker/encore/Dockerfile
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
       --tag ${CI_REGISTRY}/medleybox/encore:latest
      -f docker/encore/Dockerfile
      .
    - docker push ${CI_REGISTRY}/medleybox/encore:latest