version: '3.4'

x-variables: &x-variables
    APP_ENV: dev
    APP_SECRET: c95ab68cbfba3232e79d72ebae567424
    TZ: Europe/London
    POSTGRES_USER: medleybox
    POSTGRES_DB: medleybox_webapp
    POSTGRES_PASSWORD: medleybox

volumes:
    minio-data:
    postgres-data:
    redis-data:

networks:
    medley:
        external: true

services:
    nginx:
        image: medleybox/nginx
        restart: always
        networks:
            - medley
        ports:
            - "80:80"
            - "443:443"
    webapp:
        image: medleybox/webapp
        restart: always
        environment: *x-variables
        networks:
            - medley
    redis:
        image: redis:alpine
        restart: always
        environment: *x-variables
        networks:
            - medley
        volumes:
            - redis-data:/data
    db:
        image: postgres:12-alpine
        restart: always
        environment: *x-variables
        networks:
            - medley
        volumes:
         - postgres-data:/var/lib/postgresql/data
