version: '3.4'

x-variables: &x-variables
    APP_DEBUG: 1
    APP_ENV: dev
    APP_SECRET: c95ab68cbfba3232e79d72ebae567424
    TZ: Europe/London
    POSTGRES_USER: medleybox
    POSTGRES_DB: medleybox_webapp
    POSTGRES_PASSWORD: medleybox
    MAILER_DSN: smtp://mailhog:1025

volumes:
    minio-data:
    postgres-data:
    redis-data:

networks:
    medley:
        external: true

services:
    nginx:
        image: ghcr.io/medleybox/nginx:master
        restart: always
        environment: *x-variables
        build:
            context: ../nginx/
            dockerfile: ../nginx/Dockerfile
        depends_on:
            - "encore"
            - "webapp"
            - "mailhog"
        volumes:
         - ./public/build:/var/www/public/build
        networks:
            - medley
        ports:
            - "80:80"
            - "443:443"
    encore:
        image: ghcr.io/medleybox/encore:master
        extra_hosts:
         - "medleybox.local:0.0.0.0"
        networks:
            - medley
        volumes:
         - ./assets:/app/assets
         - ./public/build:/app/public/build
        build:
            context: ./
            dockerfile: docker/encore/Dockerfile
    webapp:
        image: ghcr.io/medleybox/webapp:master
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        restart: always
        environment: *x-variables
        networks:
            - medley
        volumes:
         - ./bin/run-tests:/var/www/bin/run-tests:ro
         - ./bin/phpunit:/var/www/bin/phpunit:ro
         - ./config/packages:/var/www/config/packages
         - ./src:/var/www/src
         - ./tests:/var/www/tests
         - ./templates:/var/www/templates
         - ./vendor:/var/www/vendor
         - ./public/build:/var/www/public/build
         - ./phpstan.neon:/var/www/phpstan.neon
         - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
         - ./composer.json:/var/www/composer.json
         - ./composer.lock:/var/www/composer.lock
         - ./symfony.lock:/var/www/symfony.lock:ro
    redis:
        image: redis:alpine
        restart: always
        environment: *x-variables
        networks:
            - medley
        volumes:
            - redis-data:/data
    mailhog:
        image: mailhog/mailhog
        networks:
            - medley
    db:
        image: postgres:12-alpine
        restart: always
        environment: *x-variables
        networks:
            - medley
        volumes:
         - postgres-data:/var/lib/postgresql/data
