version: '3.4'

x-variables: &x-variables
    APP_ENV: dev
    PPM_DEBUG: 1

services:
    nginx:
        image: medleybox/nginx
        environment: *x-variables
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
    webapp:
        image: medleybox/webapp
        environment: *x-variables
        volumes:
         - ./bin:/app/bin
         - ./config:/app/config
         - ./src:/app/src
         - ./templates:/app/templates
         - ./vendor:/app/vendor
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
